title: "Adela Habib"
description: "Computational scientist working at the intersection of machine learning, computational physics/chemistry, and high-performance computing."
url: ""       # set to https://<username>.github.io in production
baseurl: ""   # set to /<repo> if deploying as a project site

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty

# Social
social:
  linkedin: "https://www.linkedin.com/in/adela-habib/"
  github: "https://github.com/adela-habib"
  scholar: "https://scholar.google.com/citations?user=yYTKXucAAAAJ&hl=en"

# Build
exclude:
  - README.md
  - user_guide.md
